apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-foo
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: ad2b69c15cc5b4d1e845e47452788f07-185310041.us-east-1.elb.amazonaws.com 
    http:
      paths:
      - path: /foo
        pathType: Prefix
        backend:
          service:
            name: server-foo
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-bar
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: ad2b69c15cc5b4d1e845e47452788f07-185310041.us-east-1.elb.amazonaws.com 
    http:
      paths:
      - path: /bar
        pathType: Prefix
        backend:
          service:
            name: server-bar
            port:
              number: 8080
---
